services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgdb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/pgdb
    command: ["sh", "./init.sh"]

volumes:
  db_data:
